project_name: engineering-career-growth
data_dir: ./data
output_dir: null
log_level: INFO
sources:
  substack:
    name: "Substack Newsletters"
    type: "substack"
    enabled: true
    seed_queries:
      - "engineering management best practices"
      - "engineering career growth frameworks"
    custom_urls:
      - "https://newsletter.pragmaticengineer.com/p/career-laddering"
      - "https://newsletter.theengineeringmanager.com/p/management-frameworks"
    limit: 10
    timeout: 30
    max_retries: 3
    cache_ttl: 86400
    source_params:
      curated_newsletters:
        - "pragmaticengineer"
        - "theengineeringmanager"
        - "engineeringorg"
        - "managementmatters"
  medium:
    type: medium
    name: Medium Articles
    enabled: true
    seed_queries:
    - software engineering
    - engineering leadership
    custom_urls: []
    limit: 10
    timeout: 30
    max_retries: 3
    cache_ttl: 86400
    source_params:
      tags:
      - software-engineering
      - software-development
      - engineering-management
      - engineering-leadership
      - tech-leadership
  youtube:
    type: youtube
    name: YouTube Videos
    enabled: true
    seed_queries:
    - software engineering career
    - engineering leadership
    custom_urls: []
    limit: 10
    timeout: 30
    max_retries: 3
    cache_ttl: 86400
    source_params: {}
  papers:
    type: papers
    name: Technical Papers
    enabled: true
    seed_queries:
    - software engineering methods
    - software team productivity
    custom_urls: []
    limit: 5
    timeout: 30
    max_retries: 3
    cache_ttl: 86400
    source_params: {}
  reddit:
    type: reddit
    name: Reddit Discussions
    enabled: true
    seed_queries:
    - engineering career growth
    - software engineering promotion
    - tech leadership advice
    custom_urls: []
    limit: 10
    timeout: 30
    max_retries: 3
    cache_ttl: 86400
    source_params:
      recommended_subreddits:
      - cscareerquestions
      - ExperiencedDevs
      - AskEngineers
      - softwareengineering
      - engineeringmanagement
      - programming
      - datascience
      - devops
      - careeradvice
processors:
  substack:
    type: substack
    enabled: true
    extract_metadata: true
    extract_text: true
    max_content_length: 100000
    processor_params: {}
  medium:
    type: medium
    enabled: true
    extract_metadata: true
    extract_text: true
    max_content_length: 100000
    processor_params: {}
  youtube:
    type: youtube
    enabled: true
    extract_metadata: true
    extract_text: true
    max_content_length: 100000
    processor_params: {}
  papers:
    type: papers
    enabled: true
    extract_metadata: true
    extract_text: true
    max_content_length: 100000
    processor_params: {}
  reddit:
    type: reddit
    enabled: true
    extract_metadata: true
    extract_text: true
    max_content_length: 100000
    processor_params: {}
evaluation:
  enabled: true
  method: standard
  criteria:
    relevance: 1.0
    quality: 1.0
    depth: 1.0
    practicality: 1.0
  min_score: 0.7
  batch_size: 10
  model: gpt-4o
  temperature: 0.3
  max_tokens: 1000
  eval_params: {}
chunking:
  enabled: false
  strategy: sliding_window
  chunk_size: 1000
  chunk_overlap: 100
  extra_params: {}
embedding:
  enabled: false
  model: text-embedding-3-small
  dimensions: 1536
  batch_size: 100
  extra_params: {}
extra_params: {}
