# Models Registry
# This file defines available AI models that can be used with Agent Factory.
# Only models with available API keys should be included here.

openai_models:
  gpt-3.5-turbo:
    provider: "openai"
    description: "OpenAI GPT-3.5 Turbo - Fast and cost-effective for most tasks"
    api_key_env: "OPENAI_API_KEY"
    capabilities: ["chat", "reasoning", "code"]
    cost_tier: "low"
    
  gpt-4:
    provider: "openai"
    description: "OpenAI GPT-4 - Most capable OpenAI model for complex reasoning"
    api_key_env: "OPENAI_API_KEY"
    capabilities: ["chat", "reasoning", "code", "analysis"]
    cost_tier: "high"
    
  gpt-4-turbo:
    provider: "openai"
    description: "OpenAI GPT-4 Turbo - Latest GPT-4 with improved performance and speed"
    api_key_env: "OPENAI_API_KEY"
    capabilities: ["chat", "reasoning", "code", "analysis", "vision"]
    cost_tier: "medium"
    
  gpt-4o-mini:
    provider: "openai"
    description: "OpenAI GPT-4o Mini - Fast and efficient for most tasks with tool calling"
    api_key_env: "OPENAI_API_KEY"
    capabilities: ["chat", "reasoning", "code", "tools"]
    cost_tier: "low"

anthropic_models:
  claude-3-sonnet:
    provider: "anthropic"
    description: "Anthropic Claude 3 Sonnet - Balanced performance and speed for most tasks"
    api_key_env: "ANTHROPIC_API_KEY"
    capabilities: ["chat", "reasoning", "analysis", "writing"]
    cost_tier: "medium"
    
  claude-3-opus:
    provider: "anthropic"
    description: "Anthropic Claude 3 Opus - Most capable Anthropic model for complex tasks"
    api_key_env: "ANTHROPIC_API_KEY"
    capabilities: ["chat", "reasoning", "analysis", "writing", "research"]
    cost_tier: "high"
    
  claude-3-haiku:
    provider: "anthropic"
    description: "Anthropic Claude 3 Haiku - Fast and efficient for simple tasks"
    api_key_env: "ANTHROPIC_API_KEY"
    capabilities: ["chat", "reasoning"]
    cost_tier: "low"

# Usage Notes:
# - Only models with available API keys will be loaded
# - cost_tier: low (most economical), medium (balanced), high (premium)
# - capabilities: list of what the model excels at
# - api_key_env: required environment variable for this model 